### ISSUE TITLE
Extend js development environment installation instruction

### ISSUE THREAD

**Issue by sobkowiak** [oasp/oasp4js#13]
I was installing the js sde last time and I was missing some information about installation of the sde. Trivial, but for non-js developer not intuitive.

After installing NodeJS, I had to install `bower` and `grunt-cli` separately

```
npm install -g grunt-cli
npm install -g  bower
```

It would be nice when the manual could be extended with such informations. I can"t find any informations how to install the software necessary for js development.

**Comment by mmatczak** [comment]
We improved our documentation at https://github.com/oasp/oasp4js. The prerequisites you can find at: https://github.com/oasp/oasp4js/wiki/Prerequisites.
