### ISSUE TITLE
cloning https://github.com/oasp/oasp4j-sample.git"

### ISSUE THREAD

**Issue by joedoehh** [oasp/oasp4js#14]
to have a working client application i followed the documentation that requested me to clone the sample application. i was not able to clone the sample application and got the following error:

git.exe clone      --progress -v  "https://github.com/oasp/oasp4j-sample.git" "C:\projects\oasp\workspaces\main\oasp4j-sample"

Cloning into 'C:\projects\oasp\workspaces\main\oasp4j-sample'...
remote: Repository not found.
fatal: repository 'https://github.com/oasp/oasp4j-sample.git/' not found

am i cloning with the wrong url?

**Comment by hohwille** [comment]
1. You are in the wrong tracker here oasp4j goes here:
https://github.com/oasp/oasp4j/issues

2. The repo opas4j-sample has been merged into oasp4j and been deleted:
https://github.com/oasp/oasp4j/issues/137
Is there any instructions left pointing to that URL you where trying to checkout?

3. Simply ignore the step to clone oasp4j-sample and just use oasp4j and you shall be fine.

**Comment by hohwille** [comment]
This is the instructions I wrote and that should be up-to-date:
https://github.com/oasp/oasp4j/wiki/oasp-ide-setup

**Comment by joedoehh** [comment]
step 10 in the instruction you provided points and instructs to install oasp4j-sample:
"Check out oasp4js-sample and build it - see OASP4JS setup."

as you say its up to date, but also suggest to ignore install oasp4 - in the end the only thing i want to know is how to start a web client for the sample application

**Comment by hohwille** [comment]
yep, but you tried to check out oasp4j-sample instead of oasp4js-sample (4j vs. 4js).
