### ISSUE TITLE
Build script for generated client

### ISSUE THREAD

**Issue by Max-Goebel** [oasp/oasp4js#30]
Is there any reason why the yeoman generator does not generate a pom.xml for building the application? The whole java-directory is missing. Or have I totally misunderstood anything?

**Comment by hohwille** [comment]
IMHO the yeoman template was designed for creating a oasp4js only app.
In oasp4js we will ship a maven archetype with OASP4J server AND OASP4JS client in one project.
This will then also be accomplished with according code-templates for generating CRUD from entity to UI. Be patient :)

**Comment by MarcoRose** [comment]
This issue is handled in https://github.com/oasp/oasp4j/issues/214. We will track the progress there.
