### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by aburghcap** [oasp/oasp4js#31]
We can further simplify creating new OASP4JS apps by providing a .gitignore knowing which directories and files are maintained by the build process (e.g. gulp serve) and so to be excluded from version control.

What about copying the .gitignore from OASP4JS into oasp-generator?

**Comment by hohwille** [comment]
What is actually left to do?
https://github.com/oasp/oasp4j/blob/develop/.gitignore
https://github.com/oasp/oasp4js/blob/development/.gitignore

Maybe it is not part of the app template. I also have these in my global gitconfig so in my case there is never anything left to do.

**Comment by hohwille** [comment]
Yup. Not in archetype. So is your suggestion to add it to our archetype?

**Comment by aburghcap** [comment]
closed - no further work planned on this
