### ISSUE TITLE
tablemanagement/v1/table/ID/marktableas service not available anymore

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4js#33]
We currently observe, that the oasp4js client tries to access the `/tablemanagement/v1/table/ID/marktableas/STATE` service while for example occupying a table.
As this service has been replaced by a simple `/tablemanagement/v1/saveTable` service, we should adapt the client to this new service.
See [TableManamgentRestServiceImpl of the OASP4J Sample](https://github.com/oasp/oasp4j/blob/develop/oasp4j-samples/oasp4j-sample-core/src/main/java/io/oasp/gastronomy/restaurant/tablemanagement/service/impl/rest/TablemanagementRestServiceImpl.java) for more detail.

**Comment by hohwille** [comment]
See also #29.
BTW the saveTable is a ```POST``` on ```/tablemanagement/v1/table```.

**Comment by lgoerlach** [comment]
Fixed in PR https://github.com/oasp/oasp4js/pull/36.

**Comment by MarcoRose** [comment]
resolved
