### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by mmatczak** [oasp/oasp4js#50]
Validation should be implemented based on the following rules:
1) for simple syntactic validation the valdr framework should be employed.
2) for cross-field validation the ui-validate directive should be used
3) for asynchronous validation the angular $asyncValidators should be used
4) for server side validation modal dialogs / growl messages (described separately in...)

Pre-Tasks:
1) Migration to ui-router (https://github.com/oasp/oasp4js/issues/51)
2) Order Details dialog should not be implemented as a modal one

Post-Task:
1) Bread Crumb (separate task)

**Comment by dumbNickname** [comment]
When reviewing code related to this issue please refer to pull requests: 
- https://github.com/oasp/oasp4js/pull/58
- https://github.com/oasp/oasp4js/pull/62
- https://github.com/oasp/oasp4js/pull/67
