### ISSUE TITLE
Usage of jQuery $ in application and tests - conventions.

### ISSUE THREAD

**Issue by dumbNickname** [oasp/oasp4js#55]
Hi,

While going through the code I have noticed that jQuery $ is being used in test for language-change directive. I have replaced that with angular.element, but then I have also noticed that $ is an allowed global variable in jsHint rules. Are there any conventions concerning the usage of $ already established? 
Imho, angular.element should be used wherever jqLite functionality is enough - allows to avoid introducing unnecessary dependency on jQuery where it is simply not needed. 

There is also another side of the equation. When jQuery is included in the project then its functionality will be exposed under angular.element. When application grows it might be hard to distinguish where real jQuery functionality is needed. I would propose to use $ only in such cases to explicitly express our intention, however I would suppress jshint only in those files where $ is needed - those cases should be rather rare (if we do not overuse jQueryUI based components). 

Cheers,
Bartek

**Comment by dumbNickname** [comment]
I can see that there is no interest to comment on this topic so I close this issue as it concerns only code conventions.

**Comment by hohwille** [comment]
IMHO jQuery is a very nice framework to simplify DOM manipulations, etc. However, frameworks like AngularJS take you to another level or dimension of client development where you typically do not have to deal with such stuff anymore. I personally did not see any need for this. However, I am sure that if more projects come on top of oasp4js there might also arise such need. Then we can still reopen...
