### ISSUE TITLE
After login no content is available

### ISSUE THREAD

**Issue by ksola** [oasp/oasp4js#69]
In the sample application I logging as waiter and no tables are available.
![image](https://cloud.githubusercontent.com/assets/4560553/10447537/8d22d060-7185-11e5-89c0-f413b2da5735.png)
The same happen when the user is logged into cook
![image](https://cloud.githubusercontent.com/assets/4560553/10447574/d20c5b56-7185-11e5-899d-85ebc8f106b4.png)

**Comment by hohwille** [comment]
The debugger seems to reveal that the content has been received from the server. Did you observe this problem on the latest code from the develop branch when locally starting with "gulp serve"?

**Comment by dumbNickname** [comment]
I have just checked the application from commit # 7db90439b52273814987cb13c0a9c6045fee3623 (currently the head of development branch) and the tables are being displayed properly in my local environment. 
I can already say that you are using development branch as Error Log is already present in the navigation bar. I will try to clean my env and reproduce your problem. I will let you know if I face similar problems.

**Comment by ksola** [comment]
Yes, I have checked it on the latest code from develop branch when starting with "gulp serve"

**Comment by dumbNickname** [comment]
I have asked @ksola to check if application works properly when oasp4j server is taken from stable master branch (instead of development) as I have also faced some problems with websockets when using server from development branch. Now we wait for some (hopefully) good news :P

**Comment by MarcoRose** [comment]
Norbert Klein reportet the same with his local installation, but definitely saw the data being transferred on the network to the browser.

**Comment by dumbNickname** [comment]
Problem should be solved by https://github.com/oasp/oasp4js/pull/71. I would like one of the admins to have a look and merge it (btw. some other pull requests are hanging). My write access to the main repository is missing for some reason, so I cannot do it on my own : )

**Comment by szendo** [comment]
I also had this problem. After the marge with #71 everything works fine.

**Comment by may-bee** [comment]
will be fixed with #79 without reverting to instable dependency resolution.

**Comment by jkokoszk** [comment]
Fixed with PR #71
