### ISSUE TITLE
Guided Project TH Köln - 1.2: Add list of recipes as an entry point for recipe management

### ISSUE THREAD

**Issue by aburghcap** [oasp/oasp4js#78]
Part of the Guided Project at Technische Hochschule Köln - #48

As an entry point for recipe management operations we add a list of recipes to the restaurant sample application where cooks or other users can search for existing recipes and add new ones.

This dialog enables a user
- searching for text in titles or even descriptions of recipes
- paging through a list of recipes (to potentially cope with at least some dozens hits)
- selecting a potentially relevant recipe to get more details about it.

The dialog will be made available by adding a new menu item beneath the existing ones.
## Requirements

a) listing a potentially tall number of entries (with paging)
b) nice format showing the title of recipes in a bold font and their description in a small font underneath
c) search input field filtering the recipes list to those containing a string as part of their title (optionally description)
d) search should be performed on server-side for being able to cope with potentially big numbers of recipes
e) selecting a single recipe shows some more details on the right side beneath the list so that the user can evaluate multiple recipes with little effort
f) the list should look self explaining (without the need for column titles) and well designed
## UI design

![recipeslistatrecipespage_issue](https://cloud.githubusercontent.com/assets/11456980/11086401/f4fbade2-8850-11e5-9a49-9ef8fcc7cab4.JPG)

With details for the selected recipe:
![recipeslistwithdetailsatrecipespage_issue 78](https://cloud.githubusercontent.com/assets/11456980/11086597/f5189388-8852-11e5-8e80-686b9ed8c9b6.JPG)

**Comment by szendo** [comment]
Have we enough space for details?
on screenshots i see that no
Maybe bootstrap collapse? On click or on hover ?

**Comment by aburghcap** [comment]
closed - no further work planned on this
