### ISSUE TITLE
Releasing OASP4JS with shrinkwrap

### ISSUE THREAD

**Issue by may-bee** [oasp/oasp4js#87]
I do not know whether you already suggest to use shrinkwrap as mandatory tool to create releases of the oasp4js. If so, we should document a release howto similar to what we have for oasp4j, which covers such mandatory steps to be performed to enable stable release management.

**Comment by jkokoszk** [comment]
As far is I see shrinkwrap is already used but documentation is missing that's why I close this issue and create another one just for documentation
