### ISSUE TITLE
Create unique correlation ID and request counter to send with every request

### ISSUE THREAD

**Issue by hohwille** [oasp/oasp4js#90]
In OASP4J there is a concept called correlationID that is used as MDC and is included into each log entry. The idea is to be able to follow and trace a call trough the entire application landscape of a SOA or MicroServices architecture. 

Therefore the client has to include an HTTP Header ```CorrelationId``` that should be set as following:
* when the client is started a unique id (```clientId```) is created (e.g. UUID)
* when the client is started a request counter (```clientRequestCounter```) is initialized with 0
* for each request the request counter is increased and the ```CorrelationId``` is set to ```clientId```-```clientRequestCounter```.

So if ```clientId``` is ```9fbe72def1924fa``` the first request will have
```
CorrelationId: 9fbe72def1924fa-1
```

**Comment by hohwille** [comment]
UUID with JS:
https://jsfiddle.net/briguy37/2MVFd/

**Comment by hohwille** [comment]
In Angular create an interceptor as factory and register it in `config` via:
```
$httpProvider.interceptors.push('myInterceptor');
```
The interceptor has to provide a function like this:
```
request: function (config) {
  requestCounter++;
  config.headers['X-Correlation-Id'] = uuid + requestCounter;
  return config;
}
```

**Comment by hohwille** [comment]
https://github.com/oasp/oasp4j/pull/427

**Comment by maybeec** [comment]
For oasp4j, this issues can be closed. PR merged.
